title: Aeee
name: LEE, SEOYEON
description: |
  Web Developer.
email: spoi2308@gmail.com
github: Aeee90

baseurl: ""
url: "http://Aeee.github.io"

markdown: kramdown

image: '/assets/images/default_blog_cover.jpeg'
asset_url: /assets

google_analytics:
    ua: 'UA-91843902-3'